### ISSUE TITLE
sparse matrix

### ISSUE THREAD

**Issue by manuel76413** [fengwang/matrix#2]
does this head-only matrix tool support effective sparse matrix store, process, etc?

**Comment by fengwang** [comment]
> does this head-only matrix tool support effective sparse matrix store, process, etc?

@manuel76413 No. This library is designed as close as possible to STL containers, in which iterator is an essential part. When with sparse matrices, all the iterators will get invalidated, and the numeric algorithms based on iterators will get invalid as well.
